{ Vcl.ImageCollection index extracted from Source/DataFrm.dfm.
  Generated by tools/f3_image_extract.py -- do not hand-edit; re-run the tool.

  This unit carries NAMES and DIMENSIONS only. The images themselves are
  files under Source/Fpc/UI/Data/Images, byte-verified against the DFM by
  `f3_image_extract.py --verify`. FPC cannot express a multi-megabyte typed
  constant of bytes, so the payload lives on disk and this is the index.
}
unit ImageCollectionData;

interface

type
  /// One named image of one collection.
  TImageCollItem = record
    /// The DFM's `Name`. Kept because it is what a human reads, and it is
    /// what the combo boxes pair with -- but NEVER a lookup key: names
    /// repeat across a collection, so resolving by name would be ambiguous.
    Name: string;
    /// Path relative to the images root, using forward slashes so the
    /// manifest and the unit mean the same thing on every platform.
    FileName: string;
    Width: Integer;
    Height: Integer;
  end;

  TImageCollectionRec = record
    Name: string;
    /// In index order. Index order IS the contract: every call site drives
    /// these controls by `ImageIndex`, never by name.
    Items: array of TImageCollItem;
  end;

const
  /// ImageThemeColection: 9 item(s).
  IMAGETHEMECOLECTION_NAMES: array[0..8] of string = (
    'Windows Classic',
    'Windows Classic 10',
    'Windows10SlateGray',
    'Windows 10 Blue Whale',
    'blackpearl',
    'glossy',
    'calypso',
    'flatui',
    'materialblue'
  );
  IMAGETHEMECOLECTION_FILES: array[0..8] of string = (
    'ImageThemeColection/00_windows_classic.png',
    'ImageThemeColection/01_windows_classic_10.png',
    'ImageThemeColection/02_windows10slategray.png',
    'ImageThemeColection/03_windows_10_blue_whale.png',
    'ImageThemeColection/04_blackpearl.png',
    'ImageThemeColection/05_glossy.png',
    'ImageThemeColection/06_calypso.png',
    'ImageThemeColection/07_flatui.png',
    'ImageThemeColection/08_materialblue.png'
  );
  IMAGETHEMECOLECTION_WIDTHS: array[0..8] of Integer = (
    671,
    670,
    670,
    672,
    671,
    671,
    671,
    671,
    671
  );
  IMAGETHEMECOLECTION_HEIGHTS: array[0..8] of Integer = (
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250
  );

  /// EMBTImageCollection: 2 item(s).
  EMBTIMAGECOLLECTION_NAMES: array[0..1] of string = (
    'EMBTBlack',
    'EMBTWhite'
  );
  EMBTIMAGECOLLECTION_FILES: array[0..1] of string = (
    'EMBTImageCollection/00_embtblack.png',
    'EMBTImageCollection/01_embtwhite.png'
  );
  EMBTIMAGECOLLECTION_WIDTHS: array[0..1] of Integer = (
    139,
    139
  );
  EMBTIMAGECOLLECTION_HEIGHTS: array[0..1] of Integer = (
    23,
    23
  );

  /// AppearanceThemeCollection: 9 item(s).
  APPEARANCETHEMECOLLECTION_NAMES: array[0..8] of string = (
    'windows_classic',
    'windows_10',
    'slate_gray',
    'blue_whale',
    'black_pearl',
    'glossy',
    'calypso',
    'flat_ui_light',
    'material_patterns'
  );
  APPEARANCETHEMECOLLECTION_FILES: array[0..8] of string = (
    'AppearanceThemeCollection/00_windows_classic.png',
    'AppearanceThemeCollection/01_windows_10.png',
    'AppearanceThemeCollection/02_slate_gray.png',
    'AppearanceThemeCollection/03_blue_whale.png',
    'AppearanceThemeCollection/04_black_pearl.png',
    'AppearanceThemeCollection/05_glossy.png',
    'AppearanceThemeCollection/06_calypso.png',
    'AppearanceThemeCollection/07_flat_ui_light.png',
    'AppearanceThemeCollection/08_material_patterns.png'
  );
  APPEARANCETHEMECOLLECTION_WIDTHS: array[0..8] of Integer = (
    475,
    475,
    475,
    474,
    475,
    474,
    474,
    474,
    475
  );
  APPEARANCETHEMECOLLECTION_HEIGHTS: array[0..8] of Integer = (
    249,
    248,
    248,
    248,
    248,
    249,
    249,
    250,
    248
  );

var
  /// Every collection found in DataFrm.dfm, in declaration order.
  IMAGE_COLLECTIONS: array[0..2] of TImageCollectionRec;

/// Number of extracted collections.
function ImageCollectionCount: Integer;
/// Index of the collection called AName, or -1. The DFM spells the handle
/// `dmMain.<Name>`, so the collection name is what a use site names.
function FindImageCollectionIndex(const AName: string): Integer;

implementation

uses
  Classes;

procedure FillCollection(var AColl: TImageCollectionRec; const AName: string;
  const ANames, AFiles: array of string;
  const AWidths, AHeights: array of Integer);
var
  I: Integer;
begin
  AColl.Name := AName;
  SetLength(AColl.Items, Length(ANames));
  for I := 0 to High(ANames) do
  begin
    AColl.Items[I].Name := ANames[I];
    AColl.Items[I].FileName := AFiles[I];
    AColl.Items[I].Width := AWidths[I];
    AColl.Items[I].Height := AHeights[I];
  end;
end;

function ImageCollectionCount: Integer;
begin
  Result := High(IMAGE_COLLECTIONS) + 1;
end;

function FindImageCollectionIndex(const AName: string): Integer;
var
  I: Integer;
begin
  for I := Low(IMAGE_COLLECTIONS) to High(IMAGE_COLLECTIONS) do
    if IMAGE_COLLECTIONS[I].Name = AName then
      Exit(I);
  Result := -1;
end;

initialization
  FillCollection(IMAGE_COLLECTIONS[0], 'ImageThemeColection', IMAGETHEMECOLECTION_NAMES, IMAGETHEMECOLECTION_FILES, IMAGETHEMECOLECTION_WIDTHS, IMAGETHEMECOLECTION_HEIGHTS);
  FillCollection(IMAGE_COLLECTIONS[1], 'EMBTImageCollection', EMBTIMAGECOLLECTION_NAMES, EMBTIMAGECOLLECTION_FILES, EMBTIMAGECOLLECTION_WIDTHS, EMBTIMAGECOLLECTION_HEIGHTS);
  FillCollection(IMAGE_COLLECTIONS[2], 'AppearanceThemeCollection', APPEARANCETHEMECOLLECTION_NAMES, APPEARANCETHEMECOLLECTION_FILES, APPEARANCETHEMECOLLECTION_WIDTHS, APPEARANCETHEMECOLLECTION_HEIGHTS);
end.
