// ---------------------------------------------------------------------------
// Does the LFM step 3 PRODUCES actually load, and do the icons arrive?
// =======================================================================
// Everything before this probe was text. f3_dfm_to_lfm.py rewrote
// `TSVGIconImageList` as `TLclSvgImageList` and emitted one property per list,
// and the struct gate said the control was shaped correctly. Neither fact says
// a reader can stream the result. This program is the thing that answers it.
//
// It streams the REAL generated fragments -- every *.svg-lists.lfm the
// converter emitted (DataFrm's five lists, NewProjectFrm's one) -- rather
// than an LFM the probe writes itself. A hand-written fixture would
// agree with the control by construction and prove only that the control can
// be fed something shaped like what it expects; feeding it the converter's
// actual output is what makes a converter bug visible.
//
// WHAT IS ASSERTED, AND WHY EACH ONE
// ==================================
//   1. The files stream at all. A syntax error in the rule -- a `>` that should
//      be `end>`, an item `end` the writer lost -- fails here, not in a window
//      somebody opens later.
//   2. The components come back named as the DFMs named them, and their
//      union is exactly SvgListCount. The consumer forms reference them by
//      name (`Images = dmMain.SVGImageListMenuStyle`), so a rename that the
//      converter performed silently would break every one of the 15 consumers
//      while each list still rendered.
//   3. Each Count equals the icon count f3_svg_extract.py recorded. This is the
//      cross-check against a SECOND implementation: the converter read the DFM
//      with one parser, SvgData was generated by another, and the expected
//      numbers here come from a third (the manifest). If step 3 had dropped a
//      list's payload and the control had quietly rendered what it could, this
//      is the line that notices.
//   4. Each list has Width = Height = its recorded pixel edge (19/18/32/25/37),
//      proving the edge came from the DATA and not from a DFM property that
//      happened to survive.
//   5. No list reports MissingData, and no list reports RasterFailures.
//   6. The icons have INK. Count alone is the project's recurring blind spot:
//      "structurally fine, draws nothing" has been true of the extraction
//      (12x data loss), of the control's first version (LoadSvgLists never
//      loaded anything) and of the gate over both. So every bitmap is scanned
//      for a non-clTransparent pixel, and a blank one fails here.
//
// WHY THE CLASSES ARE REGISTERED BY HAND
// ======================================
// `RegisterClass` is not optional. A component reader resolves every class name
// through FindClass, and neither TLclSvgImageList nor the carrier class is one
// of the LCL's own -- LCLClasses registers the standard widgets, not ours.
// Without the two calls below the probe would fail with "class TLclSvgImageList
// not found", which reads as a broken control rather than a missing
// registration, so the failure mode is worth the six lines.
//
// WHY THERE IS NO Application.Run
// ==============================
// Nothing here needs a message loop. `Interfaces` is still required (the
// renderer calls into the widgetset, and its absence is an EAccessViolation
// inside Render), and Application.Initialize is still called so the canvas the
// icons are drawn into belongs to a live widgetset.
// ---------------------------------------------------------------------------

{$mode objfpc}{$H+}

program SvgLfmProbe;

uses
  {$IFDEF UNIX}cthreads,{$ENDIF}
  Interfaces, Classes, SysUtils, Forms, Graphics, ImgList, LResources,
  LclSvgImageList, SvgData;

type
  // The carrier the generated fragment declares as its root. It has to exist
  // under exactly this name -- see emit_svg_fragment() in
  // tools/f3_dfm_to_lfm.py, which is what writes `object SvgImageLists:
  // TSvgImageLists` into every fragment.
  TSvgImageLists = class(TComponent);

  // The class RESOLVER. `ReadComponentFromBinaryStream` calls
  // OnFindComponentClass unconditionally, with no nil guard
  // (lcl/lresources.pp: `AClass:=nil; OnFindComponentClass(nil,AClassName,AClass)`),
  // so passing nil is not "use the default" -- it is a call through a nil
  // method pointer, which on this build hung instead of failing. The event is
  // `of object`, so it needs a host object; a plain function will not do.
  TClassResolver = class
    procedure Resolve(Reader: TReader; const AClassName: string;
                      var ComponentClass: TComponentClass);
  end;

procedure TClassResolver.Resolve(Reader: TReader; const AClassName: string;
  var ComponentClass: TComponentClass);
begin
  // FindClass, so a class that was never registered reports
  // "Class TLclSvgImageList not found" -- which is the truth and names the
  // fix -- instead of silently resolving to something else.
  ComponentClass := TComponentClass(FindClass(AClassName));
  if ComponentClass = nil then
    raise EClassNotFound.CreateFmt('Class "%s" not found', [AClassName]);
end;

const
  // The directory the converter writes the fragments into. Found by PATTERN,
  // not by a hard-coded list of file names: the extractor gains a source DFM
  // from time to time (it now reads two), and a probe that names its inputs
  // would silently stop testing a fragment nobody remembered to add.
  FRAGMENT_DIR = 'Source\Fpc\UI\Forms';

var
  Failures: Integer = 0;
  // Across every fragment. One fragment holds one form's lists, so no
  // single file is expected to carry all of SvgData -- the UNION is.
  TotalComponents: Integer = 0;
  Resolver: TClassResolver;
  Fragments: TStringList;
  K: Integer;

procedure Check(const What: string; Ok: Boolean; const Detail: string = '');
begin
  if Ok then
    WriteLn('  OK   ', What, ' ', Detail)
  else begin
    WriteLn('  FAIL ', What, ' ', Detail);
    Inc(Failures);
  end;
end;

// A bitmap whose every pixel has Alpha = 0 is an icon that did not render.
// Count says nothing about this, which is the whole point.
//
// `GetBitmap` + `Canvas.Colors[].Alpha` rather than a direct pixel read, for
// two measured reasons recorded in SvgListProbe.lpr: `Colors` is a TCanvas
// member and not a TBitmap one, and the image list hands the icon over in the
// shape a control would ask for it -- which is the thing actually under test.
function HasInk(L: TLclSvgImageList; AIndex: Integer): Boolean;
var
  Dst: TBitmap;
  X, Y: Integer;
begin
  Result := False;
  Dst := TBitmap.Create;
  try
    Dst.SetSize(L.Width, L.Height);
    L.GetBitmap(AIndex, Dst);
    for Y := 0 to Dst.Height - 1 do
      for X := 0 to Dst.Width - 1 do
        if Dst.Canvas.Colors[X, Y].Alpha <> 0 then
          Exit(True);
  finally
    Dst.Free;
  end;
end;

procedure CheckList(L: TLclSvgImageList; const Edge, WantCount: Integer);
var
  I, Blank: Integer;
begin
  WriteLn('  ', L.ListName, ':');
  Check('not MissingData', not L.MissingData);
  Check('Count', L.Count = WantCount,
        Format('got %d, want %d', [L.Count, WantCount]));
  Check('edge from SvgData', (L.Width = Edge) and (L.Height = Edge),
        Format('got %dx%d, want %d', [L.Width, L.Height, Edge]));
  Check('no raster failures', L.RasterFailures = 0,
        Format('got %d', [L.RasterFailures]));

  Blank := 0;
  for I := 0 to L.Count - 1 do
    if not HasInk(L, I) then
      Inc(Blank);
  Check('every icon has ink', Blank = 0,
        Format('%d blank of %d', [Blank, L.Count]));
end;

// Expectations are looked up BY NAME, not by position. An earlier version
// indexed a static Expected[ComponentIndex], which silently compared a
// subset against the wrong list: a fragment holding only
// SVGImageListProjectStyle was checked against SVGImageListMenuStyle's 85
// icons and 19 px and reported two failures that had nothing to do with
// the code under test. Order in an LFM is not part of any contract, so an
// expectation that depends on it is not an expectation.
function ExpectedFor(const AName: string; out Edge, Count: Integer): Boolean;
var
  K: Integer;
begin
  for K := 0 to SvgListCount - 1 do
    if SVG_IMAGE_LISTS[K].Name = AName then
    begin
      Edge := SVG_IMAGE_LISTS[K].SizePx;
      if Edge <= 0 then
        Edge := DEFAULT_ICON_EDGE;
      Count := Length(SVG_IMAGE_LISTS[K].Svg);
      Exit(True);
    end;
  Edge := 0;
  Count := 0;
  Result := False;
end;

procedure StreamFragment(const APath: string);
var
  Mem: TFileStream;
  Bin: TMemoryStream;
  Root: TComponent;
  I, Edge, Count: Integer;
begin
  WriteLn('STREAMING ', APath);
  if not FileExists(APath) then
  begin
    WriteLn('RESULT: the converter produced no fragment to test -- FAIL');
    Halt(1);
  end;

  // AnsiString, because -Mdelphiunicode makes `string` a UnicodeString and
  // TFileStream still takes an AnsiString file name in this FPC. The implicit
  // conversion compiles, but it is exactly the kind of narrowing that turns
  // a non-ASCII path into "file not found" with no diagnostic.
  Mem := TFileStream.Create(AnsiString(APath), fmOpenRead or fmShareDenyWrite);
  Bin := TMemoryStream.Create;
  try
    // Two stages, deliberately, and the split is load-bearing:
    //
    //   * NOT `TReader`. FPC 3.2.2's Classes ships only TBinaryObjectReader
    //     (`TAbstractObjectReader` has exactly one concrete subclass), and
    //     `TReader.Create` builds that one unconditionally. Pointed at a text
    //     LFM it did not fail -- it HUNG, spinning on ASCII looking for a
    //     binary signature, which is worse than an error because it reads as a
    //     deadlock in the control rather than a wrong API.
    //   * `LRSObjectTextToBinary` then `ReadComponentFromBinaryStream`, rather
    //     than `ReadComponentFromTextStream`. The combined helper does exactly
    //     these two, and separating them is what tells a malformed fragment
    //     apart from a fragment that parses but instantiates wrongly -- the
    //     difference between "the converter wrote nonsense" and "the control
    //     refused to load".
    try
      LRSObjectTextToBinary(Mem, Bin);
    except
      on E: Exception do
      begin
        WriteLn('  PARSE raised ', E.ClassName, ': ', E.Message);
        Inc(Failures);
        Halt(1);
      end;
    end;
    WriteLn('  parsed to binary: ', Bin.Size, ' byte(s)');
    Mem.Position := 0;
    Bin.Position := 0;
    Root := nil;
    try
      ReadComponentFromBinaryStream(Bin, Root, @Resolver.Resolve);
    except
      on E: Exception do
      begin
        WriteLn('  streaming raised ', E.ClassName, ': ', E.Message);
        Inc(Failures);
        Root := nil;
      end;
    end;
  finally
    Bin.Free;
    Mem.Free;
  end;
  if Root = nil then
  begin
    WriteLn('RESULT: the fragment streamed to a nil component -- FAIL');
    Halt(1);
  end;
  WriteLn('  streamed root: ', Root.ClassName, ' with ', Root.ComponentCount,
          ' component(s)');

  try
    WriteLn;
    Check('root is TSvgImageLists', Root is TSvgImageLists);
    TotalComponents := TotalComponents + Root.ComponentCount;
    WriteLn;
    for I := 0 to Root.ComponentCount - 1 do
    begin
      if not (Root.Components[I] is TLclSvgImageList) then
      begin
        Check('component ' + IntToStr(I) + ' is a TLclSvgImageList', False,
              'got ' + Root.Components[I].ClassName);
        Continue;
      end;
      if not ExpectedFor(Root.Components[I].Name, Edge, Count) then
      begin
        Check('list name is known to SvgData', False,
              Root.Components[I].Name + ' is in no SvgData record');
        Continue;
      end;
      CheckList(TLclSvgImageList(Root.Components[I]), Edge, Count);
    end;
  finally
    Root.Free;
  end;
end;

function FragmentPaths: TStringList;
var
  Search: TSearchRec;
begin
  Result := TStringList.Create;
  if FindFirst(FRAGMENT_DIR + '\*.svg-lists.lfm', faAnyFile, Search) = 0 then
  begin
    repeat
      Result.Add(FRAGMENT_DIR + '\' + Search.Name);
    until FindNext(Search) <> 0;
    FindClose(Search);
  end;
  // Deterministic order, so a failure message names fragments in the
  // same sequence on every run and on every machine.
  Result.Sort;
end;

begin
  RegisterClass(TSvgImageLists);
  RegisterClass(TLclSvgImageList);
  WriteLn('  registered both classes');
  Resolver := TClassResolver.Create;
  Application.Initialize;
  WriteLn('  Application.Initialize done');

  Fragments := FragmentPaths;
  try
    WriteLn('DISCOVERED ', Fragments.Count, ' fragment(s) in ', FRAGMENT_DIR);
    if Fragments.Count = 0 then
    begin
      WriteLn('RESULT: the converter produced no fragments to test -- FAIL');
      Halt(1);
    end;
    for K := 0 to Fragments.Count - 1 do
      StreamFragment(Fragments[K]);
  finally
    Fragments.Free;
  end;
  Resolver.Free;

  WriteLn;
  Check('union of fragments holds every SvgData list',
        TotalComponents = SvgListCount,
        Format('got %d component(s), want %d',
               [TotalComponents, SvgListCount]));
  WriteLn('Streamed lists match the data unit: ',
          Format('%d of %d', [TotalComponents, SvgListCount]));

  WriteLn;
  if Failures = 0 then
    WriteLn('RESULT: the generated LFM loads and its icons are drawn')
  else
  begin
    WriteLn('RESULT: ', Failures, ' check(s) FAILED');
    Halt(1);
  end;
end.
