#!/usr/bin/env pwsh
# Build the FPC core test directly with the compiler.
#
# lazbuild could not be used for the first attempt because its project reader
# reported "Project has no main unit" on a .lpi whose <Unit0> was correct. Going
# straight to fpc separates two questions that lazbuild conflates: can the
# COMPILER find the units, and can the project file be read.
#
# The -Fu flags are passed as an argument ARRAY. Written inline they collapse:
# PowerShell consumed every -Fu value as a new source file, which is what the
# "Only one source file supported, changing source file from ..." warnings were
# -- the search paths were silently discarded before the compiler ever saw them,
# so the run failed at the first unit for a reason that had nothing to do with
# the unit.
[CmdletBinding()]
param(
    [switch]$Win
)

$ErrorActionPreference = 'Stop'
$laz = 'C:\lazarus'
$fpcBin = Join-Path $laz 'fpc\3.2.2\bin\x86_64-win64'
$env:PATH = "$laz;$fpcBin;$env:PATH"

$proj = Join-Path $PSScriptRoot '..\Tests\FpcCoreTests'
Set-Location $proj
if (-not (Test-Path 'lib\win64')) {
    New-Item -ItemType Directory -Path 'lib\win64' -Force | Out-Null
}

# Every -Fu is ABSOLUTE. FPC resolves `System.SysUtils` against each search path
# by appending the dotted remainder, and it does that from the compiler's own
# working directory rather than the project directory -- with a relative
# `-Fufpc_alias` the alias directory was never consulted and the compile died on
# the unit that directory exists to provide. Absolute paths remove the question.
$units = @(
    (Resolve-Path '..\..\Source\Core').Path
    (Resolve-Path '..\..\Source\Debugger\GDB').Path
    (Resolve-Path '..\..\Source\LSP\JsonRpc').Path
    (Resolve-Path '..\..\Source\LSP\Transport').Path
    (Resolve-Path '..\..\Source\LSP\Process').Path
    (Resolve-Path '..\..\Source\Toolchain').Path
)

# NO fpc_alias entry here. One existed until 2026-10-05: alias shim units
# (fpc_alias/System/SysUtils.pas etc.) generated by tools/fpc_alias_gen.py.
# Both layouts were built and BOTH failed, for one reason -- FPC refuses to
# compile a unit whose name contains a dot:
#     flat    fpc_alias/System.SysUtils.pas  -> Fatal: I/O error: File not open
#     nested  fpc_alias/System/SysUtils.pas -> Illegal unit name: System.SysUtils
# The units and their generator were removed rather than left in the tree, since
# they cannot work and would invite someone to try them again. The uses clauses
# now carry both spellings under {$IFDEF FPC} instead -- see
# tools/fpc_uses_rewrite.py.

# NO -FN<scope> here. It was tried first, on the theory that FPC's namespace
# support would resolve `System.SysUtils` against a scope root. It does not:
# -FN adds dotted names to the SEARCH ORDER, it does not synthesise units, and
# with it enabled the compile still failed on System.SysUtils while the alias
# directory went unnoticed. The generated shims are what makes the names resolve.
# -Mdelphiunicode, NOT -Mdelphi.
#
# -Mdelphi is Delphi 7 mode, which has no anonymous methods, and Core.Events
# declares `TCompilerProgressHandler = reference to procedure(...)`. That is
# dialect risk #3 of doc/FPC-Lazarus渐进式移植实施方案.md §7, and the first real
# compile hit it:
#
#     Core.Events.pas(186,5) Error: Identifier not found "reference"
#
# DelphiUnicode mode is Delphi 2009+ and supports them. Measured consequence to
# watch: it also switches string handling to Unicode, so the smoke test's string
# comparisons are being exercised under different semantics than the Delphi 7
# build -- noted rather than assumed harmless.
$args = @('-Mdelphiunicode', '-FUlib\win64', '-FE.')
# -Fu takes its value ATTACHED (`-Fu<path>`). Passing it as two arguments does
# not work: fpc reads the bare path as a source file and keeps only the last one,
# which is what the "Only one source file supported, changing source file from
# ..." warnings meant. Five of the six search paths were being discarded before
# the compiler started, so the run died on the first unit for a reason that had
# nothing to do with that unit.
foreach ($u in $units) { $args += "-Fu$u" }
if ($Win) { $args += '-dTEST_TOOLCHAIN' }
$args += 'FpcCoreTests.lpr'

Write-Host "==> fpc $($args.Count) args" -ForegroundColor Cyan
& fpc @args
exit $LASTEXITCODE